View cards
vityha20022/WordFlip pull request #12
Opened 2024-03-24 18:12 UTC by vityha20022

2024-03-24 18:19 UTC, NikitaKislyakov requested changes

2024-03-24 18:19 UTC, NikitaKislyakov commented on WordFlipPackage/Sources/EntityModule/Card/CardCell.swift
> +
Удаляем комменты и пустую строку

2024-03-24 18:19 UTC, NikitaKislyakov commented on WordFlipPackage/Sources/EntityModule/Deck/DeckViewController.swift
> +
Комменты

2024-03-24 19:59 UTC, BrukhanovZahar requested changes

2024-03-24 19:59 UTC, BrukhanovZahar commented on WordFlipPackage/Sources/EntityModule/Deck/DeckViewController.swift
> +
Лишняя пустая строка

2024-03-24 19:59 UTC, BrukhanovZahar commented on WordFlipPackage/Sources/EntityModule/Deck/DeckViewController.swift
> +        var actions = [UIContextualAction]()
Не начинаем функции с пустой строки

2024-03-25 13:07 UTC, snitsaryuk approved these changes

2024-03-25 13:07 UTC, snitsaryuk commented on WordFlipPackage/Sources/EntityModule/Card/CardCell.swift
> +final class CardCell: UITableViewCell {
CardTableViewCell

2024-03-25 13:08 UTC, closed without merging