View deck redactor
vityha20022/WordFlip pull request #13
Opened 2024-03-25 13:06 UTC by vityha20022

2024-03-25 15:05 UTC, BrukhanovZahar requested changes

2024-03-25 15:05 UTC, BrukhanovZahar commented on WordFlipPackage/Sources/EntityModule/Deck/DeckRedactorViewController.swift
> +
Функции с пустой строки не начинаем

2024-03-25 15:05 UTC, BrukhanovZahar commented on WordFlipPackage/Sources/EntityModule/Deck/DeckView.swift
> +
Удалить

2024-03-25 15:05 UTC, BrukhanovZahar commented on WordFlipPackage/Sources/EntityModule/Deck/DeckView.swift
> +    private var deckNamePlaceholderText = "Type deck name..."
Было бы не плохо пустую строку вставить.

2024-03-25 15:05 UTC, BrukhanovZahar commented on WordFlipPackage/Sources/Models/Models.swift
> +
Удалить

2024-03-25 15:05 UTC, BrukhanovZahar commented on WordFlipPackage/Sources/Models/Models.swift
> +}
Может для каждой модели будем отдельный файл делать?

2024-03-25 16:20 UTC, snitsaryuk requested changes

2024-03-25 16:20 UTC, snitsaryuk commented on WordFlipPackage/Sources/EntityModule/Deck/DeckCell.swift
> +    private let deckView: DeckView = {
можно просто `private let deckView = DeckView()`

2024-03-25 16:20 UTC, snitsaryuk commented on WordFlipPackage/Sources/EntityModule/Deck/DeckRedactorViewController.swift
> +        return configuration.model.cards.count
щас так оставить ок, но будет браться из презентера

2024-03-25 16:20 UTC, snitsaryuk commented on WordFlipPackage/Sources/EntityModule/Deck/DeckRedactorViewController.swift
> +        tap.cancelsTouchesInView = false
можно убрать

2024-03-25 16:20 UTC, snitsaryuk commented on WordFlipPackage/Sources/EntityModule/Deck/DeckView.swift
> +class DeckView: UIView {
final

2024-03-25 16:20 UTC, snitsaryuk commented on WordFlipPackage/Sources/SystemDesign/DefaultButtonView.swift
> +        self.translatesAutoresizingMaskIntoConstraints = false
без self

2024-03-26 20:22 UTC, BrukhanovZahar approved these changes

2024-03-26 20:22 UTC, BrukhanovZahar commented on WordFlipPackage/Sources/EntityModule/Deck/DeckRedactorViewController.swift
> +final public class DeckRedactorViewController: UIViewController{
Лишняя пустая строка

2024-03-26 20:22 UTC, BrukhanovZahar commented on WordFlipPackage/Sources/EntityModule/Deck/DeckRedactorViewController.swift
> +    private lazy var deckView: DeckView = {
Можно без lazy

2024-03-26 22:21 UTC, snitsaryuk approved these changes

2024-03-26 22:49 UTC, merged