Add Navigation, Sign up and Log in
vityha20022/WordFlip pull request #26
Opened 2024-03-27 20:35 UTC by NikitaKislyakov

2024-03-27 21:28 UTC, snitsaryuk requested changes

2024-03-27 21:28 UTC, snitsaryuk commented on WordFlip/SceneDelegate.swift
> +        let coordinator = AppCoordinator(window: window)
координатор лучше держать, после выхода из функции он умрет

2024-03-27 21:28 UTC, snitsaryuk commented on WordFlipPackage/Sources/Authentication/Models/RegisterUserRequests.swift
> +    let eMail: String
лучше email

2024-03-27 21:28 UTC, snitsaryuk commented on WordFlipPackage/Sources/Authentication/Presentors/AuthScreenPresenter.swift
> +class AuthScreenPresenter: AuthScreenPresenterProtocol {
final

2024-03-27 21:28 UTC, snitsaryuk commented on WordFlipPackage/Sources/Authentication/Presentors/AuthScreenPresenter.swift
> +    var viewController: AuthViewProtocol!
не пишем с форс анврапом

2024-03-27 21:28 UTC, snitsaryuk commented on WordFlipPackage/Sources/Authentication/Presentors/AuthScreenPresenter.swift
> +    public func auth(email: String, password: String) {
не нужен паблик

2024-03-27 21:28 UTC, snitsaryuk commented on WordFlipPackage/Sources/Authentication/Presentors/AuthScreenPresenter.swift
> +    var viewController: AuthViewProtocol!
нужен вик, тут утечка

2024-03-27 21:28 UTC, snitsaryuk commented on WordFlipPackage/Sources/Authentication/Presentors/AuthScreenPresenter.swift
> +        AuthService.shared.logInUser(with: userRequest) { error in
лучше сделать с вик селфом комплишн

2024-03-27 21:28 UTC, snitsaryuk commented on WordFlipPackage/Sources/Authentication/Presentors/RegisterScreenPresenter.swift
> +class RegisterScreenPresenter: RegisterScreenPresenterProtocol {
final

2024-03-27 21:28 UTC, snitsaryuk commented on WordFlipPackage/Sources/Authentication/Presentors/RegisterScreenPresenter.swift
> +    weak var viewController: RegisterViewProtocol!
форс анврап

2024-03-27 21:28 UTC, snitsaryuk commented on WordFlipPackage/Sources/Authentication/Presentors/RegisterScreenPresenter.swift
> +        AuthService.shared.registerUser(with: userRequest) { _, error in
лучше вик сделать

2024-03-27 21:28 UTC, snitsaryuk commented on WordFlipPackage/Sources/Authentication/Services/AuthService.swift
> +//    }
лишнее

2024-03-27 21:28 UTC, snitsaryuk commented on WordFlipPackage/Sources/Authentication/Services/AuthService.swift
> +public class AuthService {
final

2024-03-27 21:28 UTC, snitsaryuk commented on WordFlipPackage/Sources/Authentication/Services/AuthServiceProtocol.swift
> +public protocol AuthServiceProtocol {
тут не нужен протокол в целом

2024-03-27 21:28 UTC, snitsaryuk commented on WordFlipPackage/Sources/Authentication/Services/AuthServiceProtocol.swift
> +public protocol AuthServiceProtocol {
у тебя синглтон для юзера и им просто пользоваться

2024-03-27 21:28 UTC, snitsaryuk commented on WordFlipPackage/Sources/Authentication/Views/AuthViewController.swift
> +    var presenter: AuthScreenPresenterProtocol?
надо сделать let и не опционально, в ините приходит

2024-03-27 21:28 UTC, snitsaryuk commented on WordFlipPackage/Sources/Authentication/Views/AuthViewController.swift
> +
пустая строка

2024-03-27 21:28 UTC, snitsaryuk commented on WordFlipPackage/Sources/Authentication/Views/AuthViewController.swift
> +    private func didTapContinueBtn() {
лучше написать полностью button, чтобы было понятнее

2024-03-27 21:28 UTC, snitsaryuk commented on WordFlipPackage/Sources/Authentication/Views/AuthViewController.swift
> +        guard emailTextField.text != "", passwordTextField.text != "" else {
бизнес логику с проверкой переносим в презентер

2024-03-27 21:28 UTC, snitsaryuk commented on WordFlipPackage/Sources/Authentication/Views/AuthViewController.swift
> +    public func showNextScreen() {
паблики поудалять и протокол не паблик сделать

2024-03-27 21:28 UTC, snitsaryuk commented on WordFlipPackage/Sources/Authentication/Views/AuthViewController.swift
> +    private func showNoTextAlert(error: String) {
лучше приватные функции унести вниз, а интернал и паблик выше

2024-03-27 21:28 UTC, snitsaryuk commented on WordFlipPackage/Sources/Authentication/Views/AuthViewController.swift
> +    }
дублируется код, объединить в один

2024-03-27 21:28 UTC, snitsaryuk commented on WordFlipPackage/Sources/Authentication/Views/AuthViewProtocol.swift
> +public protocol AuthViewProtocol: AnyObject {
паблик убрать

2024-03-27 21:28 UTC, snitsaryuk commented on WordFlipPackage/Sources/Authentication/Views/RegisterViewController.swift
> +    var presenter: RegisterScreenPresenterProtocol?
var и опциорнально убрать

2024-03-27 21:28 UTC, snitsaryuk commented on WordFlipPackage/Sources/Authentication/Views/RegisterViewController.swift
> +    public func showNextScreen() {
паблик и приватные перемешены, надо отфильровать

2024-03-27 21:28 UTC, snitsaryuk commented on WordFlipPackage/Sources/Authentication/Views/RegisterViewController.swift
> +        guard usernameTextField.text != "", emailTextField.text != "", passwordTextField.text != "" else {
бизнес логика в презентер

2024-03-27 21:28 UTC, snitsaryuk commented on WordFlipPackage/Sources/Authentication/Views/RegisterViewController.swift
> +    }
дублирование

2024-03-27 21:28 UTC, snitsaryuk commented on WordFlipPackage/Sources/Authentication/Views/RegisterViewProtocol.swift
> +public protocol RegisterViewProtocol: AnyObject {
паблик

2024-03-27 21:28 UTC, snitsaryuk commented on WordFlipPackage/Sources/WordFlipPackage/AppCoordinator.swift
> +public class AppCoordinator {
final

2024-03-27 21:28 UTC, snitsaryuk commented on WordFlipPackage/Sources/WordFlipPackage/AppCoordinator.swift
> +            let nav = UINavigationController()
nav -> navigationController

2024-03-27 21:28 UTC, snitsaryuk commented on WordFlipPackage/Sources/WordFlipPackage/AppCoordinator.swift
> +
пустые строки

2024-03-27 22:11 UTC, vityha20022 requested changes

2024-03-27 22:11 UTC, vityha20022 commented on WordFlipPackage/Sources/Authentication/Views/AuthViewController.swift
> +        textField.textContentType = .oneTimeCode
Почему такой тип? Он же для одноразовых кодов, а не паролей

2024-03-27 22:11 UTC, vityha20022 commented on WordFlipPackage/Sources/Authentication/Views/RegisterViewController.swift
> +        textField.textContentType = .oneTimeCode
Тот же вопрос про .oneTimeCode

2024-03-27 22:11 UTC, vityha20022 commented on WordFlipPackage/Sources/Authentication/Views/RegisterViewController.swift
> +        super.init(nibName: nil, bundle: nil)
отступ между super

2024-03-27 22:11 UTC, vityha20022 commented on WordFlipPackage/Sources/Authentication/Views/RegisterViewController.swift
> +        view.backgroundColor = .black
Используй цвета из ассетов - для светлой темы экран тоже будет черным?

2024-03-27 22:11 UTC, vityha20022 commented on WordFlipPackage/Sources/WordFlipPackage/AppCoordinator.swift
> +        }
много дублирующегося кода в if else, у тебя по сути весь код одинаковый и весь его можно вынести за if else , кроме присваивания класса в mainView

2024-03-27 22:44 UTC, vityha20022 approved these changes

2024-03-28 10:19 UTC, snitsaryuk approved these changes

2024-03-28 10:21 UTC, merged