Add colors and DefaultButton class
vityha20022/WordFlip pull request #3
Opened 2024-03-20 15:48 UTC by vityha20022

2024-03-20 16:45 UTC, snitsaryuk requested changes

2024-03-20 16:45 UTC, snitsaryuk commented on WordFlipPackage/Sources/SystemDesign/Colors.swift
> +//}
комменты такие не пушим в пр

2024-03-20 16:45 UTC, snitsaryuk commented on WordFlipPackage/Sources/SystemDesign/Colors.swift
> +    }
может просто `public static let accent = UIColor(named: "AccentColor")!`
тут можно force unwrap чтобы увидеть что неправильно написал цвет/не добавил его в ассеты

2024-03-20 16:45 UTC, snitsaryuk commented on WordFlipPackage/Sources/SystemDesign/DefaultButtonView.swift
> +public class DefaultButton: UIButton {
`public final class`
пишем везде final если от класса не наследуются

2024-03-20 16:45 UTC, snitsaryuk commented on WordFlipPackage/Sources/SystemDesign/Colors.swift
> +public enum MyColors: CaseIterable {
лучше не MyColors, а что-то более осмысленное - например, ColorScheme

2024-03-20 16:45 UTC, snitsaryuk commented on WordFlipPackage/Sources/SystemDesign/DefaultButtonView.swift
> +    private var color = UIColor.clear
сделать let и ставить дефолтное значение

2024-03-20 16:45 UTC, snitsaryuk commented on WordFlipPackage/Sources/SystemDesign/DefaultButtonView.swift
> +        layer.shadowColor = UIColor(red: 0, green: 0, blue: 0, alpha: 0.25).cgColor
цвет в темной и светлой теме не должен быть разным?

2024-03-20 17:32 UTC, PaulDotSimon commented on WordFlipPackage/Sources/SystemDesign/DefaultButtonView.swift
> +        layer.shadowColor = UIColor(red: 0, green: 0, blue: 0, alpha: 0.25).cgColor
Вроде решили, что нет

2024-03-21 08:58 UTC, PaulDotSimon approved these changes

2024-03-21 09:46 UTC, snitsaryuk approved these changes

2024-03-21 10:04 UTC, merged