Dev
vityha20022/WordFlip pull request #47
Opened 2024-03-29 11:47 UTC by vityha20022

2024-04-07 19:36 UTC, BrukhanovZahar requested changes

2024-04-07 19:36 UTC, BrukhanovZahar commented on WordFlipPackage/README.md
Написать описание проекта

2024-04-07 19:36 UTC, BrukhanovZahar commented on WordFlipPackage/Sources/Authentication/StringExtension.swift
> +
Удалить

2024-04-07 19:36 UTC, BrukhanovZahar commented on WordFlipPackage/Sources/Authentication/Views/RegisterViewController.swift
> +//import Builder
Удалить

2024-04-07 19:36 UTC, BrukhanovZahar commented on WordFlipPackage/Sources/EntityModule/Deck/ViewController/DecksViewController.swift
> +        //tableView.allowsSelection = false
удалить

2024-04-07 19:36 UTC, BrukhanovZahar commented on WordFlipPackage/Sources/EntityModule/EntityDataManager.swift
> +        // TODO: Get decks from firebase
Удалить

2024-04-07 19:36 UTC, BrukhanovZahar commented on WordFlipPackage/Sources/EntityModule/EntityDataManager.swift
> +        if let savedDeckId = UserDefaults.standard.string(forKey: "CurrentDeckId") {
Удалить

2024-04-07 19:36 UTC, BrukhanovZahar commented on WordFlipPackage/Sources/EntityModule/EntityDataManager.swift
> +        decks = [firstDeck, secondDeck]*/
Удалить

2024-04-07 19:36 UTC, BrukhanovZahar commented on WordFlipPackage/Sources/EntityModule/EntityDataManager.swift
> +        // TODO: Save state in firebase
Удалить

2024-04-07 19:36 UTC, BrukhanovZahar commented on WordFlipPackage/Sources/MainView/CardsPresenter.swift
> +        }
Удалить

2024-04-07 19:36 UTC, BrukhanovZahar commented on WordFlipPackage/Sources/MainView/StackCardsView.swift
> +        //print("Add \(cardView.dataSource?.id) view: \(cardView.dataSource?.guessCounter)")
Удалить

2024-04-07 19:36 UTC, BrukhanovZahar commented on WordFlipPackage/Sources/Models/DeckModel.swift
> +        // TODO: Get from app settings
Удалить

2024-04-07 19:36 UTC, BrukhanovZahar commented on WordFlipPackage/Sources/SystemDesign/DefaultButtonView.swift
> +        // TODO: set settings size
Удалить

2024-04-07 19:36 UTC, BrukhanovZahar commented on WordFlipPackage/Sources/WordFlipPackage/ViewController.swift
Выпилить

2024-04-07 22:02 UTC, BrukhanovZahar approved these changes

2024-04-08 12:35 UTC, NikitaKislyakov requested changes

2024-04-08 12:35 UTC, NikitaKislyakov commented on WordFlipPackage/Sources/Authentication/Views/AuthViewController.swift
> +        self.topAnchorOfAuthLabel?.constant = -self.contentView.safeAreaLayoutGuide.layoutFrame.height * 0.3
значение topAnchorOfAuthLabel будет другим, перерассчитать

2024-04-08 12:35 UTC, NikitaKislyakov commented on WordFlipPackage/Sources/Authentication/Views/AuthViewController.swift
> +
скролл вью скорее всего можно убрать

2024-04-08 12:35 UTC, NikitaKislyakov commented on WordFlipPackage/Sources/Authentication/Views/EnterViewController.swift
> +    }
перенести логику в презентер

2024-04-08 12:35 UTC, NikitaKislyakov commented on WordFlipPackage/Sources/Authentication/Views/RegisterViewController.swift
> +        self.topAnchorOfRegisterLabel?.constant = -self.contentView.safeAreaLayoutGuide.layoutFrame.height * 0.34
значение будет другим, перерасчитать

2024-04-08 12:35 UTC, NikitaKislyakov commented on WordFlipPackage/Sources/EntityModule/Card/Cell/CardCell.swift
> +    }
модель с вью не взаимодействует

2024-04-08 12:35 UTC, NikitaKislyakov commented on WordFlipPackage/Sources/EntityModule/Card/Presenter/CardRedactorPresenterProtocol.swift
> +    }
модель

2024-04-08 12:35 UTC, NikitaKislyakov commented on WordFlipPackage/Sources/EntityModule/Card/Presenter/CardRedactorPresenterProtocol.swift
> +    func didTapTranslaste(sourceLanguage: Language?, targetLanguage: Language?, text: String) {
опечатка в названии метода

2024-04-08 12:35 UTC, NikitaKislyakov commented on WordFlipPackage/Sources/EntityModule/Card/View/CardView.swift
> +                textView.text = model.frontText
без моделей во вью

2024-04-08 12:35 UTC, NikitaKislyakov commented on WordFlipPackage/Sources/EntityModule/Deck/Presenter/DecksPresenterProtocol.swift
> +final class DecksPrersenter: DecksPresenterProtocol {
опечатка в названии презентера

2024-04-08 12:35 UTC, NikitaKislyakov commented on WordFlipPackage/Sources/EntityModule/Deck/ViewController/DecksViewController.swift
> +    }
лучше не обновлять таблицу во viewWillAppear

2024-04-08 12:35 UTC, NikitaKislyakov commented on WordFlipPackage/Sources/MainView/CardsViewController.swift
> +        //make.isHidden = true
лишние коммы

2024-04-08 12:35 UTC, NikitaKislyakov commented on WordFlipPackage/Sources/MainView/StackCardsView.swift
> +            let cardModel = CardModel(deckId: "", frontText: "Choose deck or reload", downText: "Choose deck or reload")
нужно локализовать

2024-04-08 12:35 UTC, NikitaKislyakov commented on WordFlipPackage/Sources/MainView/StackCardsView.swift
> +                let cardModel = CardModel(deckId: "", frontText: "Choose deck or reload", downText: "Choose deck or reload")
локализовать

2024-04-08 12:35 UTC, NikitaKislyakov commented on WordFlipPackage/Sources/ProfilePackage/ViewController/ProfileViewController.swift
> +            """,
Локализовать

2024-04-08 14:14 UTC, NikitaKislyakov commented on WordFlipPackage/Sources/Authentication/Services/AuthService.swift
> +        Database.database().isPersistenceEnabled = true
здесь только 24 строчка имеется в виду...

2024-04-08 19:12 UTC, BrukhanovZahar commented on WordFlipPackage/Sources/EntityModule/Deck/ViewController/DecksViewController.swift
> +    }
Это фиксит какой-то баг

2024-04-08 19:26 UTC, merged