View decks
vityha20022/WordFlip pull request #6
Opened 2024-03-22 21:27 UTC by vityha20022

2024-03-22 21:29 UTC, vityha20022 commented on WordFlipPackage/Sources/EditorModule/DeckViewController.swift
> +}
Для того, чтобы не использовать этот длинный код можно просто завести в ассетах картинку с круглым цветным фоном и использовать ее вместо того, чтобы создавать ее таким образом. Или так оставить норм?

2024-03-22 21:52 UTC, PaulDotSimon requested changes

2024-03-22 21:52 UTC, PaulDotSimon commented on WordFlipPackage/Sources/EditorModule/DeckCell.swift
> +class DeckCell: UITableViewCell {
вроде не наследуемся от DeckCell, можно поставить final

2024-03-22 21:52 UTC, PaulDotSimon commented on WordFlipPackage/Sources/EditorModule/DeckCell.swift
> +    let cellView: UIView = {
можно private

2024-03-22 21:52 UTC, PaulDotSimon commented on WordFlipPackage/Sources/EditorModule/DeckCell.swift
> +    let titleLabel: UILabel = {
тоже самое и с остальными, private

2024-03-22 21:52 UTC, PaulDotSimon commented on WordFlipPackage/Sources/EditorModule/DeckCell.swift
> +
пустая лишняя строка

2024-03-22 21:52 UTC, PaulDotSimon commented on WordFlipPackage/Sources/EditorModule/DeckViewController.swift
> +public class DeckViewController: UIViewController {
final

2024-03-23 08:34 UTC, snitsaryuk requested changes

2024-03-23 08:34 UTC, snitsaryuk commented on WordFlipPackage/Sources/EditorModule/DeckCell.swift
> +        NSLayoutConstraint.activate([
предпочтитетельно в одном массиве активировать сразу все констрейнты, у тебя сверху и тут активация

2024-03-23 08:34 UTC, snitsaryuk commented on WordFlipPackage/Sources/EditorModule/DeckViewController.swift
> +        let margins = view.safeAreaLayoutGuide
это не margins уже, а safeArea

2024-03-23 08:34 UTC, snitsaryuk commented on WordFlipPackage/Sources/EditorModule/DeckViewController.swift
> +        NSLayoutConstraint.activate([
лучше в одном массиве все констрейнты активировать

2024-03-23 08:34 UTC, snitsaryuk commented on WordFlipPackage/Sources/EditorModule/DeckViewController.swift
> +}
так оставить норм

2024-03-23 16:59 UTC, snitsaryuk approved these changes

2024-03-23 17:34 UTC, PaulDotSimon approved these changes

2024-03-24 16:25 UTC, merged