View authentication
vityha20022/WordFlip pull request #8
Opened 2024-03-23 16:06 UTC by NikitaKislyakov

2024-03-23 16:39 UTC, BrukhanovZahar commented on WordFlip/SceneDelegate.swift
> +        window?.rootViewController = AuthViewController()
Мы решили не добавлять эти изменения, оставь ViewController()

2024-03-23 16:39 UTC, BrukhanovZahar commented on WordFlipPackage/Package.swift
> +                     ])
Нужно удалить, мы не добавляем в products library

2024-03-23 16:39 UTC, BrukhanovZahar commented on WordFlipPackage/Package.swift
> +            dependencies: ["SystemDesign",
Вроде как не надо добавлять SystemDesign, хватит только Authentication

2024-03-23 16:39 UTC, BrukhanovZahar commented on WordFlipPackage/Sources/Authentication/AuthViewController.swift
> +
Не добавляем комментарии

2024-03-23 16:39 UTC, BrukhanovZahar commented on WordFlipPackage/Sources/Authentication/AuthViewController.swift
> +
Слишком много пустых строк

2024-03-23 16:39 UTC, BrukhanovZahar commented on WordFlipPackage/Sources/Authentication/AuthViewController.swift
> +public class AuthViewController: UIViewController {
Если от class не наследуется добавляем final

2024-03-23 16:39 UTC, BrukhanovZahar commented on WordFlipPackage/Sources/Authentication/AuthViewController.swift
> +}
Зачем в extension, можно же в AuthViewController написать

2024-03-23 16:39 UTC, BrukhanovZahar commented on WordFlipPackage/Sources/Authentication/EnterViewController.swift
> +
Тоже удалить

2024-03-23 16:39 UTC, BrukhanovZahar commented on WordFlipPackage/Sources/Authentication/EnterViewController.swift
> +
Много пустых строк

2024-03-23 16:39 UTC, BrukhanovZahar commented on WordFlipPackage/Sources/Authentication/RegisterViewController.swift
> +
Удалить

2024-03-23 16:39 UTC, BrukhanovZahar commented on WordFlipPackage/Sources/Authentication/RegisterViewController.swift
> +public class RegisterViewController: UIViewController {
Не наследуемся - пишем final

2024-03-23 16:39 UTC, BrukhanovZahar commented on WordFlipPackage/Tests/WordFlipPackageTests/WordFlipPackageTests.swift
> +       // XCTAssertEqual(WordFlipPackage().text, "Hello, World!")
Зачем тесты закоментил?

2024-03-23 17:07 UTC, snitsaryuk requested changes

2024-03-23 17:07 UTC, snitsaryuk commented on WordFlip.xcodeproj/project.pbxproj
> +		55B7B17B2BADC6B400EA7AA9 /* WordFlipPackage in Frameworks */ = {isa = PBXBuildFile; productRef = 55B7B17A2BADC6B400EA7AA9 /* WordFlipPackage */; };
а тут что-то менял с пакетами? или твой хкод сам поменял

2024-03-23 17:07 UTC, snitsaryuk commented on WordFlipPackage/Sources/Authentication/AuthViewController.swift
> +    private var scrollView: UIScrollView = {
тут и ниже можно let выставить, оно не меняется же

2024-03-23 17:07 UTC, snitsaryuk commented on WordFlipPackage/Sources/Authentication/AuthViewController.swift
> +    private func layout() {
метод называется layout, хотя тут добавляются вьюхи

2024-03-23 17:07 UTC, snitsaryuk commented on WordFlipPackage/Sources/Authentication/AuthViewController.swift
> +    func addingObservers() {
`addObservers` и го приватным

2024-03-23 17:07 UTC, snitsaryuk commented on WordFlipPackage/Sources/Authentication/AuthViewController.swift
> +        UIView.animate(withDuration: 2) {
долгое время анимации, обычно 0.3 юзается как у эпла

2024-03-23 17:07 UTC, snitsaryuk commented on WordFlipPackage/Sources/Authentication/EnterViewController.swift
> +    private var birdImageView: UIImageView = {
let

2024-03-23 17:07 UTC, snitsaryuk commented on WordFlipPackage/Sources/Authentication/RegisterViewController.swift
> +    private var scrollView: UIScrollView = {
let везде

2024-03-23 22:19 UTC, BrukhanovZahar requested changes

2024-03-23 22:19 UTC, BrukhanovZahar commented on WordFlip/SceneDelegate.swift
> +        window?.rootViewController = AuthViewController()
Ты так и не поменял

2024-03-23 22:19 UTC, BrukhanovZahar commented on WordFlipPackage/Sources/Authentication/Views/AuthViewController.swift
> +
Функции не начинаем с пустой строки

2024-03-24 08:41 UTC, snitsaryuk requested changes

2024-03-24 08:41 UTC, snitsaryuk commented on WordFlipPackage/Sources/Authentication/Views/RegisterViewController.swift
> +
лишняя строка

2024-03-24 15:44 UTC, BrukhanovZahar approved these changes

2024-03-24 19:58 UTC, snitsaryuk approved these changes

2024-03-24 20:18 UTC, merged