View profile
vityha20022/WordFlip pull request #9
Opened 2024-03-23 17:20 UTC by BrukhanovZahar

2024-03-23 17:35 UTC, NikitaKislyakov commented on WordFlipPackage/Sources/ProfilePackage/ViewController/ProfileViewController.swift
> +    private let exitButton = DefaultButton(text: "Выход", color: BaseColorScheme.red)
Меняем русский текст на английский

2024-03-23 17:37 UTC, NikitaKislyakov commented on WordFlipPackage/Sources/ProfilePackage/ViewController/ProfileViewController.swift
> +        } else {
Зачем ячейки захардкодил?

2024-03-23 17:38 UTC, NikitaKislyakov commented on WordFlipPackage/Sources/ProfilePackage/ViewController/SettingsViewController.swift
> +    }
view вроде в отдельной функции в subview лучше добавлять

2024-03-23 17:39 UTC, BrukhanovZahar commented on WordFlipPackage/Sources/ProfilePackage/ViewController/ProfileViewController.swift
> +        } else {
Это просто заглушка, котом будем через presenter нормально делать

2024-03-23 17:42 UTC, NikitaKislyakov requested changes

2024-03-23 17:42 UTC, NikitaKislyakov commented on WordFlipPackage/Sources/ProfilePackage/ViewController/SettingsViewController.swift
> +    }
view вроде в отдельной функции в subview лучше добавлять

2024-03-23 17:42 UTC, NikitaKislyakov commented on WordFlipPackage/Sources/ProfilePackage/ViewController/ProfileViewController.swift
> +    private let exitButton = DefaultButton(text: "Выход", color: BaseColorScheme.red)
Меняем русский текст на английский

2024-03-23 17:42 UTC, NikitaKislyakov commented on WordFlipPackage/Sources/ProfilePackage/ViewController/ProfileViewController.swift
> +        } else {
Зачем ячейки захардкодил?

2024-03-23 17:43 UTC, BrukhanovZahar commented on WordFlipPackage/Sources/ProfilePackage/ViewController/ProfileViewController.swift
> +        } else {
Это просто заглушка, котом будем через presenter нормально делать

2024-03-23 17:50 UTC, snitsaryuk requested changes

2024-03-23 17:50 UTC, snitsaryuk commented on WordFlipPackage/Sources/ProfilePackage/CustomCell/CustomCellProtocoll.swift
> +public protocol CustomCellProtocoll: UITableViewCell {
а зачем протокол так еще и публичный?

2024-03-23 17:50 UTC, snitsaryuk commented on WordFlipPackage/Sources/ProfilePackage/CustomCell/DefaultTableViewCell.swift
> +    required init?(coder Decoder: NSCoder) {
порядок обычно в классе такой: переменные, иниты, функции

2024-03-23 17:50 UTC, snitsaryuk commented on WordFlipPackage/Sources/ProfilePackage/CustomCell/SettingsSwitchTableViewCell.swift
> +    func configure(image: UIImage?, text: String?, isOn: Bool?) {
вместо Bool? лучше юзать просто Bool

2024-03-23 17:50 UTC, snitsaryuk commented on WordFlipPackage/Sources/ProfilePackage/ViewController/ProfileViewController.swift
> +    private func configureCell(cell: inout CustomCellProtocoll, for indexPath: IndexPath) {
лучше потом убрать inout, щас ок оставить, но с презентором переделать

2024-03-23 17:50 UTC, snitsaryuk commented on WordFlipPackage/Sources/ProfilePackage/ViewController/SettingsViewController.swift
> +
в начале функции пустые строчки не оставляем

2024-03-23 18:22 UTC, BrukhanovZahar commented on WordFlipPackage/Sources/ProfilePackage/CustomCell/CustomCellProtocoll.swift
> +public protocol CustomCellProtocoll: UITableViewCell {
Сделал internal, использую чтобы во всех custom cell гарантировать реализацию метода configure, который в дальнейшем использую для настройки ячеек

2024-03-24 08:43 UTC, snitsaryuk approved these changes

2024-03-24 12:36 UTC, NikitaKislyakov approved these changes

2024-03-24 12:38 UTC, merged